language: java

sudo: false

#cache:
#  directories:
#    - $HOME/.m2

before_script:
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - unset GEM_PATH GEM_HOME IRBRC JRUBY_OPTS
  - "export PATH=`pwd`/bin:$PATH"
  - echo $HOME

jdk:
  - openjdk7
#  - oraclejdk8

os:
  - linux

env:
  global:
    - MALLOC_ARENA_MAX=2
  matrix:
    - JT='test specs :language'
    - JT='test specs :core'
    - JT='test specs :library'
    - JT='test specs :truffle'
    - JT='test integration'

matrix:
  include:
    - env: COMMAND=test/check_versions.sh
      jdk: oraclejdk8
    #- env: JT=check_ambiguous_arguments
    #  jdk: oraclejdk8
  allow_failures:
    - env: PHASE='-Prake -Dtask=test:mri:fullint'
    - env: JT=check_ambiguous_arguments
      jdk: oraclejdk8
    - env: JT='test mri'
    - env: JTR='ci --batch ../lib/ruby/truffle/jruby+truffle/gem_ci/travis.txt'
    # NOTE: build seems to never start (waited for any to finish for more than a day) - probably a travis-ci bug
    #- env: PHASE='-Pmain'
    #  sudo: required
    #  dist: trusty
    #  group: edge
    #  jdk: oraclejdk9

branches:
  only:
    - master
    - jruby-1_7
    - truffle-head
    - /^test-.*$/
    - /^ha-feature/
    - ruby-2.3

script: tool/travis_runner.sh
install: travis_retry ./mvnw -Pbootstrap clean install -B -Dinvoker.skip -Dmaven.test.skip

notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true

  # update jruby-head installed on Travis CI
  webhooks:
    urls:
      - "https://rubies.travis-ci.org/rebuild/jruby-head"
# we are on a branch
    on_success: always
    on_failure: never
