language: java
before_script:
  - unset GEM_PATH GEM_HOME IRBRC
  - "export PATH=`pwd`/bin:$PATH"

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  matrix:
    - TARGET='test-extended'
#    - TARGET='spec:ci_interpreted_travis'
#    - TARGET='spec:ci_interpreted_ir_travis'
#    - TARGET='spec:ir'
#    - TARGET='spec:truffle'
#    - TARGET='test-dist'

matrix:
  include:
    - env: ''
      script: mvn test -Ptest -Pmain
      jdk: oraclejdk7
    - env: ''
      script: mvn test -Ptest -Pcomplete
      jdk: oraclejdk8
    - env: ''
      script: mvn -Pdist
      jdk: oraclejdk8
    - env: ''
      script: mvn -Pjruby-jars
      jdk: oraclejdk7
  fast_finish: true
  allow_failures:
    - env: TARGET='spec:ci_interpreted_ir_travis'
    - env: TARGET='test-dist'
    - jdk: oraclejdk8

branches:
  only:
    - master
    - jruby-1_7
    - /^test-.*$/

before_install:
  - if [[ $TRAVIS_JDK_VERSION = 'oraclejdk8' ]]; then sudo apt-get update; sudo apt-get install oracle-java8-installer; else true; fi

# run the bootstrap twice due to https://github.com/jruby/jruby/issues/1497
script: echo travis_fold:start:bootstrap && mvn -Pbootstrap && echo travis_fold:end:bootstrap && ant $TARGET"
install: /bin/true
notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"

  # update jruby-head installed on Travis CI
  webhooks:
    urls:
      - "https://rubies.travis-ci.org/rebuild/jruby-head"
# we are on a branch
    #on_success: always
    on_failure: never
