version: '{build}'

build: off

environment:
  global:
    - MAVEN_OPTS: -Xmx2g
    - JAVA_OPTS: -Xmx2g
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

install:
  - cmd: echo %PATH%
  - cmd: java -version
  - mvn -X -v

cache:
  - C:\Users\appveyor\.m2\repository -> pom.rb

test_script:
  - mvn -Ptest
